<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="5" time="0.121" timestamp="2021-04-09T20:24:44.809027" hostname="LAPTOP-MA82NGKA"><testcase classname="sample_test" name="test_fun" time="0.001" /><testcase classname="sample_test" name="test_fun1" time="0.001"><failure message="assert 4 == 5&#10; +  where 4 = fun(3)">@pytest.mark.search
    def test_fun1():
&gt;       assert fun(3)==5
E       assert 4 == 5
E        +  where 4 = fun(3)

sample_test.py:11: AssertionError</failure></testcase><testcase classname="test_add" name="test_answer" time="0.001" /><testcase classname="test_sample" name="test_answer" time="0.001" /><testcase classname="test_sample" name="test_answer1" time="0.001"><failure message="assert 4 == 5&#10; +  where 4 = inc(3)">@pytest.mark.login
    def test_answer1():
&gt;       assert inc(3) == 5
E       assert 4 == 5
E        +  where 4 = inc(3)

test_sample.py:12: AssertionError</failure></testcase></testsuite></testsuites>